const students = [
    {
      full_name: "John Doe",
      description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
      gender: "male",
      available: true,
      calendly: "https://calendly.com/johndoe",
      pdf: "https://example.com/johndoe.pdf",
      linkedIn: "https://linkedin.com/in/johndoe",
      skills: ["JavaScript", "HTML", "CSS"],
      job_types: ["Full-time", "Internship"],
      languages: ["English", "Spanish"],
      majors: ["Computer Science", "Information Technology"]
    },
    {
      full_name: "Jane Smith",
      description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
      gender: "female",
      available: false,
      calendly: "https://calendly.com/janesmith",
      pdf: "https://example.com/janesmith.pdf",
      linkedIn: "https://linkedin.com/in/janesmith",
      skills: ["Python", "Data Analysis", "SQL"],
      job_types: ["Part-time", "Freelance"],
      languages: ["English", "French"],
      majors: ["Statistics", "Mathematics"]
    },
    {
      full_name: "Michael Johnson",
      description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
      gender: "male",
      available: true,
      calendly: "https://calendly.com/michaeljohnson",
      pdf: "https://example.com/michaeljohnson.pdf",
      linkedIn: "https://linkedin.com/in/michaeljohnson",
      skills: ["Java", "Spring Boot", "SQL"],
      job_types: ["Full-time"],
      languages: ["English"],
      majors: ["Computer Science"]
    },
    {
      full_name: "Emily Williams",
      description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
      gender: "female",
      available: true,
      calendly: "https://calendly.com/emilywilliams",
      pdf: "https://example.com/emilywilliams.pdf",
      linkedIn: "https://linkedin.com/in/emilywilliams",
      skills: ["C++", "Data Structures", "Algorithms"],
      job_types: ["Internship"],
      languages: ["English", "Spanish", "German"],
      majors: ["Computer Science"]
    },
    {
      full_name: "Robert Brown",
      description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
      gender: "male",
      available: false,
      calendly: "https://calendly.com/robertbrown",
      pdf: "https://example.com/robertbrown.pdf",
      linkedIn: "https://linkedin.com/in/robertbrown",
      skills: ["Ruby", "Ruby on Rails", "JavaScript"],
      job_types: ["Full-time", "Part-time"],
      languages: ["English"],
      majors: ["Computer Science"]
    },
    {
      full_name: "Olivia Davis",
      description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
      gender: "female",
      available: true,
      calendly: "https://calendly.com/oliviadavis",
      pdf: "https://example.com/oliviadavis.pdf",
      linkedIn: "https://linkedin.com/in/oliviadavis",
      skills: ["PHP", "MySQL", "Laravel"],
      job_types: ["Full-time", "Remote"],
      languages: ["English", "French"],
      majors: ["Web Development"]
    },
    {
      full_name: "William Wilson",
      description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
      gender: "male",
      available: true,
      calendly: "https://calendly.com/williamwilson",
      pdf: "https://example.com/williamwilson.pdf",
      linkedIn: "https://linkedin.com/in/williamwilson",
      skills: ["Python", "Machine Learning", "TensorFlow"],
      job_types: ["Internship"],
      languages: ["English"],
      majors: ["Data Science"]
    },
    {
      full_name: "Sophia Johnson",
      description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
      gender: "female",
      available: false,
      calendly: "https://calendly.com/sophiajohnson",
      pdf: "https://example.com/sophiajohnson.pdf",
      linkedIn: "https://linkedin.com/in/sophiajohnson",
      skills: ["JavaScript", "React", "Node.js"],
      job_types: ["Full-time", "Freelance"],
      languages: ["English", "Spanish"],
      majors: ["Web Development"]
    },
    {
      full_name: "Daniel Anderson",
      description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
      gender: "male",
      available: true,
      calendly: "https://calendly.com/danielanderson",
      pdf: "https://example.com/danielanderson.pdf",
      linkedIn: "https://linkedin.com/in/danielanderson",
      skills: ["Java", "Spring", "Hibernate"],
      job_types: ["Full-time", "Remote"],
      languages: ["English"],
      majors: ["Computer Science"]
    },
    {
      full_name: "Ava Martinez",
      description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
      gender: "female",
      available: true,
      calendly: "https://calendly.com/avamartinez",
      pdf: "https://example.com/avamartinez.pdf",
      linkedIn: "https://linkedin.com/in/avamartinez",
      skills: ["Python", "Data Analysis", "SQL"],
      job_types: ["Internship"],
      languages: ["English", "Spanish"],
      majors: ["Statistics"]
    },
    {
      full_name: "Joseph Taylor",
      description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
      gender: "male",
      available: false,
      calendly: "https://calendly.com/josephtaylor",
      pdf: "https://example.com/josephtaylor.pdf",
      linkedIn: "https://linkedin.com/in/josephtaylor",
      skills: ["C#", ".NET", "SQL Server"],
      job_types: ["Full-time", "Part-time"],
      languages: ["English"],
      majors: ["Computer Science"]
    },
    {
      full_name: "Samantha Clark",
      description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
      gender: "female",
      available: true,
      calendly: "https://calendly.com/samanthaclark",
      pdf: "https://example.com/samanthaclark.pdf",
      linkedIn: "https://linkedin.com/in/samanthaclark",
      skills: ["JavaScript", "Vue.js", "Firebase"],
      job_types: ["Full-time", "Remote"],
      languages: ["English"],
      majors: ["Web Development"]
    },
    {
      full_name: "David Rodriguez",
      description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
      gender: "male",
      available: true,
      calendly: "https://calendly.com/davidrodriguez",
      pdf: "https://example.com/davidrodriguez.pdf",
      linkedIn: "https://linkedin.com/in/davidrodriguez",
      skills: ["Java", "Spring Boot", "MySQL"],
      job_types: ["Full-time"],
      languages: ["English", "Spanish"],
      majors: ["Computer Science"]
    },
    {
      full_name: "Mia Anderson",
      description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
      gender: "female",
      available: false,
      calendly: "https://calendly.com/miaanderson",
      pdf: "https://example.com/miaanderson.pdf",
      linkedIn: "https://linkedin.com/in/miaanderson",
      skills: ["Python", "Data Science", "Machine Learning"],
      job_types: ["Internship", "Part-time"],
      languages: ["English", "French"],
      majors: ["Data Science"]
    },
    {
      full_name: "Ethan Thompson",
      description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
      gender: "male",
      available: true,
      calendly: "https://calendly.com/ethanthompson",
      pdf: "https://example.com/ethanthompson.pdf",
      linkedIn: "https://linkedin.com/in/ethanthompson",
      skills: ["C++", "Algorithms", "Data Structures"],
      job_types: ["Full-time"],
      languages: ["English"],
      majors: ["Computer Science"]
    },
    {
      full_name: "Isabella White",
      description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
      gender: "female",
      available: true,
      calendly: "https://calendly.com/isabellawhite",
      pdf: "https://example.com/isabellawhite.pdf",
      linkedIn: "https://linkedin.com/in/isabellawhite",
      skills: ["JavaScript", "React", "Node.js"],
      job_types: ["Full-time", "Remote"],
      languages: ["English", "Spanish"],
      majors: ["Web Development"]
    }
];

export default students;